name: Build and Release

on:
  push:
    branches: [ master ]

jobs:
  relseae:
    name: Relseasing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build
      - name: Configure CMake
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE
      - name: Build
        env:
          AUTHOR: LeonLi
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: |
          echo $AUTHOR
          cmake --build . --config $BUILD_TYPE
      - name: Push Tag
        uses: anothrNick/github-tag-action@1.17.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
        id: bump_version
      - name: Upload HelloWorld
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          file: build/main
          asset_name: main
          tag: ${{steps.bump_version.outputs.new_tag}}
          overwrite: true
